//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shanuMVCUserRoles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Application
    {
        public int clientID { get; set; }
        public string ClientTypeSeller { get; set; }
        public string ClientTypeBuyer { get; set; }
        public string ClientTypeOwner { get; set; }
        public string FirstName { get; set; }
        public string ClientIdentityNumber { get; set; }
        public string ClientContactPerson { get; set; }
        public string ClientTelNumber { get; set; }
        public string ClientEmailAddress { get; set; }
        public string ClientPhysicalAddress { get; set; }
    }
}
